### PR TITLE
Highlight we dont have account access or hours

### PR DESCRIPTION
**Pull request by urielsalis**

### CODE REVIEW

**Comment by LordRalex** [comment]
It doesn't read right, it's 2 different combinations that don't really go together.

**Comment by urielsalis** [comment]
What do you suggest?

**Comment by LordRalex** [comment]
Break it up into 2 sentences

**Comment by LordRalex** [comment]
Deploy preview for *youthful-colden-6bf88b* failed.

Built with commit bb5ed654e3abdd6c6ab0be9e19a1a85e9bdfa424

https://app.netlify.com/sites/youthful-colden-6bf88b/deploys/5d49cef9b5c369000913272d

**Pull request merged**
